/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountUpdaterInquirySummary } from './accountUpdaterInquirySummary';

/**
* An Account Updater job.
*/
export class AccountUpdaterJob {
    /**
    * The type of this resource. Is always `account-updater-job`.
    */
    'type'?: AccountUpdaterJob.TypeEnum;
    /**
    * The unique identifier for this Account Updater job.
    */
    'id'?: string;
    /**
    * The unique ID for a merchant account.
    */
    'merchantAccountId'?: string;
    /**
    * The date and time when this Account Updater job was created.
    */
    'createdAt'?: Date;
    /**
    * The date and time when this Account Updater job was last updated.
    */
    'updatedAt'?: Date;
    /**
    * A list of inquiries associated with this Account Updater job.
    */
    'inquiries'?: Array<AccountUpdaterInquirySummary>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AccountUpdaterJob.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "merchantAccountId",
            "baseName": "merchant_account_id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "inquiries",
            "baseName": "inquiries",
            "type": "Array<AccountUpdaterInquirySummary>"
        }    ];

    static getAttributeTypeMap() {
        return AccountUpdaterJob.attributeTypeMap;
    }
}

export namespace AccountUpdaterJob {
    export enum TypeEnum {
        AccountUpdaterJob = <any> 'account-updater-job'
    }
}
