/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Details for a Apple Pay payment method.
*/
export class ApplePayRequest {
    /**
    * `applepay`.
    */
    'method': ApplePayRequest.MethodEnum;
    /**
    * The encrypted (opaque) token that was passed to the `onpaymentauthorized` callback by the Apple Pay integration.
    */
    'token': object;
    /**
    * Last 4 digits of the PAN for identification purposes.
    */
    'cardSuffix'?: string | null;
    /**
    * The scheme/brand of the card.
    */
    'cardScheme'?: string | null;
    /**
    * The type of card.
    */
    'cardType'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "ApplePayRequest.MethodEnum"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "object"
        },
        {
            "name": "cardSuffix",
            "baseName": "card_suffix",
            "type": "string"
        },
        {
            "name": "cardScheme",
            "baseName": "card_scheme",
            "type": "string"
        },
        {
            "name": "cardType",
            "baseName": "card_type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApplePayRequest.attributeTypeMap;
    }
}

export namespace ApplePayRequest {
    export enum MethodEnum {
        Applepay = <any> 'applepay'
    }
}
