/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* BIN lookup request context.
*/
export class BINLookupRequestContext {
    /**
    * The response body received from the `url`.
    */
    'response'?: string | null;
    /**
    * The response status code received from the `url`.
    */
    'responseStatusCode'?: number;
    /**
    * Whether the BIN lookup was successful or not.
    */
    'success'?: boolean;
    /**
    * The value used to lookup BIN details.
    */
    'bin'?: string | null;
    /**
    * The instrument type used to lookup BIN details.
    */
    'instrument'?: string | null;
    /**
    * The type of card, i.e. credit or debit, from the lookup response.
    */
    'type'?: string | null;
    /**
    * The card scheme result from the lookup response.
    */
    'scheme'?: BINLookupRequestContext.SchemeEnum;
    /**
    * The card additional schemes from the lookup response.
    */
    'additionalSchemes'?: Array<BINLookupRequestContext.AdditionalSchemesEnum>;
    /**
    * The card country code result from the lookup response.
    */
    'countryCode'?: string | null;
    /**
    * Whether the issuing bank supports network tokenization for this card.
    */
    'supportsNetworkTokens'?: boolean | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "response",
            "baseName": "response",
            "type": "string"
        },
        {
            "name": "responseStatusCode",
            "baseName": "response_status_code",
            "type": "number"
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "bin",
            "baseName": "bin",
            "type": "string"
        },
        {
            "name": "instrument",
            "baseName": "instrument",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "scheme",
            "baseName": "scheme",
            "type": "BINLookupRequestContext.SchemeEnum"
        },
        {
            "name": "additionalSchemes",
            "baseName": "additional_schemes",
            "type": "Array<BINLookupRequestContext.AdditionalSchemesEnum>"
        },
        {
            "name": "countryCode",
            "baseName": "country_code",
            "type": "string"
        },
        {
            "name": "supportsNetworkTokens",
            "baseName": "supports_network_tokens",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return BINLookupRequestContext.attributeTypeMap;
    }
}

export namespace BINLookupRequestContext {
    export enum SchemeEnum {
        Accel = <any> 'accel',
        Amex = <any> 'amex',
        Bancontact = <any> 'bancontact',
        CarteBancaire = <any> 'carte-bancaire',
        Cirrus = <any> 'cirrus',
        Culiance = <any> 'culiance',
        Dankort = <any> 'dankort',
        DinersClub = <any> 'diners-club',
        Discover = <any> 'discover',
        EftposAustralia = <any> 'eftpos-australia',
        Elo = <any> 'elo',
        Hipercard = <any> 'hipercard',
        Jcb = <any> 'jcb',
        Maestro = <any> 'maestro',
        Mastercard = <any> 'mastercard',
        Mir = <any> 'mir',
        Nyce = <any> 'nyce',
        Other = <any> 'other',
        Pulse = <any> 'pulse',
        Rupay = <any> 'rupay',
        Star = <any> 'star',
        Uatp = <any> 'uatp',
        Unionpay = <any> 'unionpay',
        Visa = <any> 'visa',
        Null = <any> 'null'
    }
    export enum AdditionalSchemesEnum {
        Accel = <any> 'accel',
        Amex = <any> 'amex',
        Bancontact = <any> 'bancontact',
        CarteBancaire = <any> 'carte-bancaire',
        Cirrus = <any> 'cirrus',
        Culiance = <any> 'culiance',
        Dankort = <any> 'dankort',
        DinersClub = <any> 'diners-club',
        Discover = <any> 'discover',
        EftposAustralia = <any> 'eftpos-australia',
        Elo = <any> 'elo',
        Hipercard = <any> 'hipercard',
        Jcb = <any> 'jcb',
        Maestro = <any> 'maestro',
        Mastercard = <any> 'mastercard',
        Mir = <any> 'mir',
        Nyce = <any> 'nyce',
        Other = <any> 'other',
        Pulse = <any> 'pulse',
        Rupay = <any> 'rupay',
        Star = <any> 'star',
        Uatp = <any> 'uatp',
        Unionpay = <any> 'unionpay',
        Visa = <any> 'visa',
        Null = <any> 'null'
    }
}
