/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CardRequiredFields } from './cardRequiredFields';

/**
* Details about a card.
*/
export class CardDetails {
    /**
    * `card-detail`.
    */
    'type'?: CardDetails.TypeEnum;
    /**
    * The 8 digit BIN of the card. When looking up card details using a `payment_method_id` this value will be `null`.
    */
    'id'?: string;
    /**
    * The type of card.
    */
    'cardType'?: CardDetails.CardTypeEnum;
    /**
    * The scheme/brand of the card.
    */
    'scheme'?: string;
    /**
    * The 2-letter ISO code of the issuing country of the card.
    */
    'country'?: string;
    'requiredFields'?: CardRequiredFields;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CardDetails.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "cardType",
            "baseName": "card_type",
            "type": "CardDetails.CardTypeEnum"
        },
        {
            "name": "scheme",
            "baseName": "scheme",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "requiredFields",
            "baseName": "required_fields",
            "type": "CardRequiredFields"
        }    ];

    static getAttributeTypeMap() {
        return CardDetails.attributeTypeMap;
    }
}

export namespace CardDetails {
    export enum TypeEnum {
        CardDetail = <any> 'card-detail'
    }
    export enum CardTypeEnum {
        Credit = <any> 'credit',
        Debit = <any> 'debit'
    }
}
