/**
 * Gr4vy API (Beta)
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CardDetails } from './cardDetails';

/**
* A mini format version of the card.
*/
export class CardTokenized {
    /**
    * `payment-method`.
    */
    'type'?: CardTokenized.TypeEnum;
    /**
    * The unique ID of the payment method.
    */
    'id'?: string;
    /**
    * `card`.
    */
    'method'?: CardTokenized.MethodEnum;
    'details'?: CardDetails;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CardTokenized.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "CardTokenized.MethodEnum"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "CardDetails"
        }    ];

    static getAttributeTypeMap() {
        return CardTokenized.attributeTypeMap;
    }
}

export namespace CardTokenized {
    export enum TypeEnum {
        PaymentMethod = <any> 'payment-method'
    }
    export enum MethodEnum {
        Card = <any> 'card'
    }
}
