/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Details to store a new payment method.
*/
export class CheckoutSessionFieldsPaymentMethod {
    /**
    * `card`.
    */
    'method': CheckoutSessionFieldsPaymentMethod.MethodEnum;
    /**
    * The 13-19 digit number for this card as it can be found on the front of the card.
    */
    'number'?: string;
    /**
    * The expiration date of the card, formatted `MM/YY`.
    */
    'expirationDate'?: string;
    /**
    * The 3 or 4 digit security code often found on the card. This often referred to as the CVV or CVD.  The security code can only be set if the stored payment method represents a card.
    */
    'securityCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "CheckoutSessionFieldsPaymentMethod.MethodEnum"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "string"
        },
        {
            "name": "securityCode",
            "baseName": "security_code",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CheckoutSessionFieldsPaymentMethod.attributeTypeMap;
    }
}

export namespace CheckoutSessionFieldsPaymentMethod {
    export enum MethodEnum {
        Card = <any> 'card'
    }
}
