/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CheckoutSessionPaymentMethodDetails {
    /**
    * First six digits of PAN.
    */
    'bin'?: string | null;
    'cardType'?: CheckoutSessionPaymentMethodDetails.CardTypeEnum;
    /**
    * ISO 3166 two letter country code.
    */
    'cardCountry'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bin",
            "baseName": "bin",
            "type": "string"
        },
        {
            "name": "cardType",
            "baseName": "card_type",
            "type": "CheckoutSessionPaymentMethodDetails.CardTypeEnum"
        },
        {
            "name": "cardCountry",
            "baseName": "card_country",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CheckoutSessionPaymentMethodDetails.attributeTypeMap;
    }
}

export namespace CheckoutSessionPaymentMethodDetails {
    export enum CardTypeEnum {
        Credit = <any> 'credit',
        Debit = <any> 'debit',
        Prepaid = <any> 'prepaid'
    }
}
