/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Comments to merchant or beneficiary written by customer.
*/
export class ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments {
    /**
    * Comments the customer left to the merchant.
    */
    'userCommentsToMerchant'?: string | null;
    /**
    * Comments the customer left to the beneficiary of the purchase made.
    */
    'messageToBeneficiary'?: string | null;
    /**
    * Comments by the merchant.
    */
    'merchantComments'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userCommentsToMerchant",
            "baseName": "user_comments_to_merchant",
            "type": "string"
        },
        {
            "name": "messageToBeneficiary",
            "baseName": "message_to_beneficiary",
            "type": "string"
        },
        {
            "name": "merchantComments",
            "baseName": "merchant_comments",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionOptionsForterAntiFraudCartItemsInnerBeneficiariesInnerComments.attributeTypeMap;
    }
}

