/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Additional options for Cybersource Decision Manager (anti-fraud).
*/
export class ConnectionOptionsCybersourceAntiFraud {
    /**
    * This is a key-value object for merchant defined data.
    */
    'merchantDefinedData'?: { [key: string]: string; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "merchantDefinedData",
            "baseName": "merchant_defined_data",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionOptionsCybersourceAntiFraud.attributeTypeMap;
    }
}

