/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Additional options to be passed through to Adyen when processing card transactions.
*/
export class ConnectionOptionsAdyenCard {
    /**
    * A key-value object representing additional data to be passed to Adyen.
    */
    'additionalData'?: { [key: string]: string; };
    /**
    * Enabled Adyen\'s auto-rescue feature.
    */
    'autoRescue'?: boolean = false;
    /**
    * Defines the number of days to auto-retry a payment for if `autoRescue` is enabled.
    */
    'maxDaysToRescue'?: number | null;
    /**
    * Defines the Adyen auto-rescue test scenario to invoke.
    */
    'autoRescueScenario'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "additionalData",
            "baseName": "additionalData",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "autoRescue",
            "baseName": "autoRescue",
            "type": "boolean"
        },
        {
            "name": "maxDaysToRescue",
            "baseName": "maxDaysToRescue",
            "type": "number"
        },
        {
            "name": "autoRescueScenario",
            "baseName": "autoRescueScenario",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionOptionsAdyenCard.attributeTypeMap;
    }
}

