/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionOptionsPaypalPaypalAdditionalData } from './connectionOptionsPaypalPaypalAdditionalData';

/**
* Additional options to be passed through to PayPal when processing transactions.
*/
export class ConnectionOptionsPaypalPaypal {
    /**
    * An array with key-value objects representing additional data to be passed to PayPal.
    */
    'additionalData'?: Array<ConnectionOptionsPaypalPaypalAdditionalData>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "additionalData",
            "baseName": "additional_data",
            "type": "Array<ConnectionOptionsPaypalPaypalAdditionalData>"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionOptionsPaypalPaypal.attributeTypeMap;
    }
}

