/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionOptionsAdyenCard } from './connectionOptionsAdyenCard';
import { ConnectionOptionsCybersourceAntiFraud } from './connectionOptionsCybersourceAntiFraud';
import { ConnectionOptionsCybersourceCard } from './connectionOptionsCybersourceCard';
import { ConnectionOptionsForterAntiFraud } from './connectionOptionsForterAntiFraud';
import { ConnectionOptionsPaypalPaypal } from './connectionOptionsPaypalPaypal';
import { ConnectionOptionsStripeCard } from './connectionOptionsStripeCard';

export class ConnectionOptions {
    'cybersourceCard'?: ConnectionOptionsCybersourceCard | null;
    'cybersourceAntiFraud'?: ConnectionOptionsCybersourceAntiFraud | null;
    'forterAntiFraud'?: ConnectionOptionsForterAntiFraud | null;
    'adyenCard'?: ConnectionOptionsAdyenCard | null;
    'paypalPaypal'?: ConnectionOptionsPaypalPaypal | null;
    'paypalPaypalpaylater'?: ConnectionOptionsPaypalPaypal | null;
    'stripeCard'?: ConnectionOptionsStripeCard | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cybersourceCard",
            "baseName": "cybersource-card",
            "type": "ConnectionOptionsCybersourceCard"
        },
        {
            "name": "cybersourceAntiFraud",
            "baseName": "cybersource-anti-fraud",
            "type": "ConnectionOptionsCybersourceAntiFraud"
        },
        {
            "name": "forterAntiFraud",
            "baseName": "forter-anti-fraud",
            "type": "ConnectionOptionsForterAntiFraud"
        },
        {
            "name": "adyenCard",
            "baseName": "adyen-card",
            "type": "ConnectionOptionsAdyenCard"
        },
        {
            "name": "paypalPaypal",
            "baseName": "paypal-paypal",
            "type": "ConnectionOptionsPaypalPaypal"
        },
        {
            "name": "paypalPaypalpaylater",
            "baseName": "paypal-paypalpaylater",
            "type": "ConnectionOptionsPaypalPaypal"
        },
        {
            "name": "stripeCard",
            "baseName": "stripe-card",
            "type": "ConnectionOptionsStripeCard"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionOptions.attributeTypeMap;
    }
}

