/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionOptionsForterAntiFraudAddress } from './connectionOptionsForterAntiFraudAddress';
import { ConnectionOptionsForterAntiFraudComments } from './connectionOptionsForterAntiFraudComments';
import { ConnectionOptionsForterAntiFraudPersonalDetails } from './connectionOptionsForterAntiFraudPersonalDetails';
import { ConnectionOptionsForterAntiFraudPhone } from './connectionOptionsForterAntiFraudPhone';

export class ConnectionOptionsForterAntiFraudBeneficiaries {
    'personalDetails': ConnectionOptionsForterAntiFraudPersonalDetails;
    'address'?: ConnectionOptionsForterAntiFraudAddress | null;
    /**
    * List of all phone numbers for the beneficiary.
    */
    'phone'?: Array<ConnectionOptionsForterAntiFraudPhone>;
    'comments'?: ConnectionOptionsForterAntiFraudComments | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "personalDetails",
            "baseName": "personal_details",
            "type": "ConnectionOptionsForterAntiFraudPersonalDetails"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "ConnectionOptionsForterAntiFraudAddress"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "Array<ConnectionOptionsForterAntiFraudPhone>"
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "ConnectionOptionsForterAntiFraudComments"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionOptionsForterAntiFraudBeneficiaries.attributeTypeMap;
    }
}

