/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* General data regarding item such as name, price, etc.
*/
export class ConnectionOptionsForterAntiFraudBasicItemData {
    /**
    * Tangible if physical item, non-tangible if any other product.
    */
    'type'?: ConnectionOptionsForterAntiFraudBasicItemData.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ConnectionOptionsForterAntiFraudBasicItemData.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ConnectionOptionsForterAntiFraudBasicItemData.attributeTypeMap;
    }
}

export namespace ConnectionOptionsForterAntiFraudBasicItemData {
    export enum TypeEnum {
        Tangible = <any> 'TANGIBLE',
        NonTangible = <any> 'NON_TANGIBLE'
    }
}
