/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The time window for when the data was ingested to filter by.
*/
export class DetailedSettlementReportSpecParamsFiltersIngestedAt {
    /**
    * The starting boundary for when the data was ingested as a date-time placeholder value.
    */
    'start'?: DetailedSettlementReportSpecParamsFiltersIngestedAt.StartEnum;
    /**
    * The ending boundary for when the data was ingested as a date-time placeholder value.
    */
    'end'?: DetailedSettlementReportSpecParamsFiltersIngestedAt.EndEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "start",
            "baseName": "start",
            "type": "DetailedSettlementReportSpecParamsFiltersIngestedAt.StartEnum"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "DetailedSettlementReportSpecParamsFiltersIngestedAt.EndEnum"
        }    ];

    static getAttributeTypeMap() {
        return DetailedSettlementReportSpecParamsFiltersIngestedAt.attributeTypeMap;
    }
}

export namespace DetailedSettlementReportSpecParamsFiltersIngestedAt {
    export enum StartEnum {
        DayStart = <any> 'day_start'
    }
    export enum EndEnum {
        DayEnd = <any> 'day_end'
    }
}
