/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DigitalWalletClickToPayFields {
    /**
    * Unique ID assigned for digital payment application.
    */
    'digitalPaymentApplicationId'?: string;
    /**
    * Name assigned for digital payment application.
    */
    'digitalPaymentApplicationName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "digitalPaymentApplicationId",
            "baseName": "digital_payment_application_id",
            "type": "string"
        },
        {
            "name": "digitalPaymentApplicationName",
            "baseName": "digital_payment_application_name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DigitalWalletClickToPayFields.attributeTypeMap;
    }
}

