/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DigitalWalletApplePayTokenDecryptedContext } from './digitalWalletApplePayTokenDecryptedContext';

/**
* The result after decrypting an Apple Pay token.
*/
export class DigitalWalletApplePayTokenDecrypted {
    /**
    * The type of this resource. Is always `transaction-event`.
    */
    'type'?: DigitalWalletApplePayTokenDecrypted.TypeEnum;
    /**
    * The unique identifier for this event.
    */
    'id'?: string;
    /**
    * The name of this resource. Is always `digital-wallet-apple-pay-token-decrypted`.
    */
    'name'?: DigitalWalletApplePayTokenDecrypted.NameEnum;
    /**
    * The date and time when this transaction was created in our system.
    */
    'createdAt'?: Date;
    'context'?: DigitalWalletApplePayTokenDecryptedContext;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "DigitalWalletApplePayTokenDecrypted.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "DigitalWalletApplePayTokenDecrypted.NameEnum"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "DigitalWalletApplePayTokenDecryptedContext"
        }    ];

    static getAttributeTypeMap() {
        return DigitalWalletApplePayTokenDecrypted.attributeTypeMap;
    }
}

export namespace DigitalWalletApplePayTokenDecrypted {
    export enum TypeEnum {
        TransactionEvent = <any> 'transaction-event'
    }
    export enum NameEnum {
        DigitalWalletApplePayTokenDecrypted = <any> 'digital-wallet-apple-pay-token-decrypted'
    }
}
