/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlowAmountCondition } from './flowAmountCondition';
import { FlowAmountRangeCondition } from './flowAmountRangeCondition';
import { FlowAmountZeroCondition } from './flowAmountZeroCondition';
import { FlowAntiFraudDecisionCondition } from './flowAntiFraudDecisionCondition';
import { FlowBINRangeCondition } from './flowBINRangeCondition';
import { FlowBrowserLanguageCondition } from './flowBrowserLanguageCondition';
import { FlowCardCountryCondition } from './flowCardCountryCondition';
import { FlowCardSchemeCondition } from './flowCardSchemeCondition';
import { FlowCardSourceCondition } from './flowCardSourceCondition';
import { FlowCardTypeCondition } from './flowCardTypeCondition';
import { FlowCountryCondition } from './flowCountryCondition';
import { FlowCurrencyCondition } from './flowCurrencyCondition';
import { FlowMetadataCondition } from './flowMetadataCondition';
import { FlowRuleBooleanOutcome } from './flowRuleBooleanOutcome';
import { FlowRuleMethodOutcome } from './flowRuleMethodOutcome';
import { FlowRuleServiceOutcome } from './flowRuleServiceOutcome';

/**
* A request to create a flow rule.
*/
export class FlowRuleCreateRequest {
    /**
    * Description of the flow rule.
    */
    'description'?: string;
    /**
    * One or more conditions that apply for this rule. Each condition needs to match for this rule to go into effect.
    */
    'conditions'?: Array<FlowAmountCondition | FlowAmountRangeCondition | FlowAmountZeroCondition | FlowAntiFraudDecisionCondition | FlowBINRangeCondition | FlowBrowserLanguageCondition | FlowCardCountryCondition | FlowCardSchemeCondition | FlowCardSourceCondition | FlowCardTypeCondition | FlowCountryCondition | FlowCurrencyCondition | FlowMetadataCondition>;
    'outcome'?: FlowRuleBooleanOutcome | FlowRuleMethodOutcome | FlowRuleServiceOutcome;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<FlowAmountCondition | FlowAmountRangeCondition | FlowAmountZeroCondition | FlowAntiFraudDecisionCondition | FlowBINRangeCondition | FlowBrowserLanguageCondition | FlowCardCountryCondition | FlowCardSchemeCondition | FlowCardSourceCondition | FlowCardTypeCondition | FlowCountryCondition | FlowCurrencyCondition | FlowMetadataCondition>"
        },
        {
            "name": "outcome",
            "baseName": "outcome",
            "type": "FlowRuleBooleanOutcome | FlowRuleMethodOutcome | FlowRuleServiceOutcome"
        }    ];

    static getAttributeTypeMap() {
        return FlowRuleCreateRequest.attributeTypeMap;
    }
}

