/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The metadata to compare the transaction to.
*/
export class FlowMetadataConditionValue {
    /**
    * Key to metadata value to compare transaction to.
    */
    'key'?: string;
    'value'?: Array<string> | string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<string> | string"
        }    ];

    static getAttributeTypeMap() {
        return FlowMetadataConditionValue.attributeTypeMap;
    }
}

