/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Browser language conditions with a name, operator, and value.
*/
export class FlowBrowserLanguageCondition {
    /**
    * The type of match made for this rule.
    */
    'name': FlowBrowserLanguageCondition.NameEnum;
    /**
    * The comparison to make on the browser language `value`.
    */
    'operator': FlowBrowserLanguageCondition.OperatorEnum;
    /**
    * Browser language two-letter ISO 639-1 codes to compare the transaction to.
    */
    'value': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "FlowBrowserLanguageCondition.NameEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "FlowBrowserLanguageCondition.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return FlowBrowserLanguageCondition.attributeTypeMap;
    }
}

export namespace FlowBrowserLanguageCondition {
    export enum NameEnum {
        BrowserLanguage = <any> 'browser_language'
    }
    export enum OperatorEnum {
        OneOf = <any> 'is_one_of',
        NotOneOf = <any> 'is_not_one_of'
    }
}
