/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Defines the outcome of a rule in a flow where the result is a list of UUIDs for a service.
*/
export class FlowRuleServiceOutcome {
    /**
    * The type of action outcome for the given rule.
    */
    'type': FlowRuleServiceOutcome.TypeEnum;
    /**
    * Results for a given flow action.
    */
    'result': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "FlowRuleServiceOutcome.TypeEnum"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return FlowRuleServiceOutcome.attributeTypeMap;
    }
}

export namespace FlowRuleServiceOutcome {
    export enum TypeEnum {
        List = <any> 'list'
    }
}
