/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FlowAmountConditionValue } from './flowAmountConditionValue';

/**
* Amount conditions with a name, operator, and value.
*/
export class FlowAmountCondition {
    /**
    * The type of match made for this rule.
    */
    'name': FlowAmountCondition.NameEnum;
    /**
    * The comparison to make on the currency code `value`.
    */
    'operator': FlowAmountCondition.OperatorEnum;
    'value': FlowAmountConditionValue;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "FlowAmountCondition.NameEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "FlowAmountCondition.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "FlowAmountConditionValue"
        }    ];

    static getAttributeTypeMap() {
        return FlowAmountCondition.attributeTypeMap;
    }
}

export namespace FlowAmountCondition {
    export enum NameEnum {
        Amount = <any> 'amount'
    }
    export enum OperatorEnum {
        LessThan = <any> 'less_than',
        GreaterThan = <any> 'greater_than'
    }
}
