/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* BIN range conditions with a name, operator, and value.
*/
export class FlowBINRangeCondition {
    /**
    * The type of match made for this rule.
    */
    'name': FlowBINRangeCondition.NameEnum;
    /**
    * The comparison to make on the currency code `value`.
    */
    'operator': FlowBINRangeCondition.OperatorEnum;
    /**
    * BIN range to compare with the transaction.
    */
    'value': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "FlowBINRangeCondition.NameEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "FlowBINRangeCondition.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return FlowBINRangeCondition.attributeTypeMap;
    }
}

export namespace FlowBINRangeCondition {
    export enum NameEnum {
        CardBin = <any> 'card_bin'
    }
    export enum OperatorEnum {
        OneOf = <any> 'is_one_of',
        NotOneOf = <any> 'is_not_one_of'
    }
}
