/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Card type condition with a name, operator, and value.
*/
export class FlowCardTypeCondition {
    /**
    * The type of match made for this rule.
    */
    'name': FlowCardTypeCondition.NameEnum;
    /**
    * The comparison to make on the `value`.
    */
    'operator': FlowCardTypeCondition.OperatorEnum;
    /**
    * Card type to compare the transaction to.
    */
    'value': Array<FlowCardTypeCondition.ValueEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "FlowCardTypeCondition.NameEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "FlowCardTypeCondition.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<FlowCardTypeCondition.ValueEnum>"
        }    ];

    static getAttributeTypeMap() {
        return FlowCardTypeCondition.attributeTypeMap;
    }
}

export namespace FlowCardTypeCondition {
    export enum NameEnum {
        CardType = <any> 'card_type'
    }
    export enum OperatorEnum {
        OneOf = <any> 'is_one_of',
        NotOneOf = <any> 'is_not_one_of'
    }
    export enum ValueEnum {
        Credit = <any> 'credit',
        Debit = <any> 'debit',
        Prepaid = <any> 'prepaid'
    }
}
