/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Amount conditions matching a value of 0 in any currency.
*/
export class FlowAmountZeroCondition {
    /**
    * The type of match made for this rule.
    */
    'name': FlowAmountZeroCondition.NameEnum;
    /**
    * The comparison to make on the transaction `value`.
    */
    'operator': FlowAmountZeroCondition.OperatorEnum;
    /**
    * The value of the transaction must be 0.
    */
    'value': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "FlowAmountZeroCondition.NameEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "FlowAmountZeroCondition.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return FlowAmountZeroCondition.attributeTypeMap;
    }
}

export namespace FlowAmountZeroCondition {
    export enum NameEnum {
        AmountZero = <any> 'amount_zero'
    }
    export enum OperatorEnum {
        EqualTo = <any> 'equal_to'
    }
}
