/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Card country condition with a name, operator, and value.
*/
export class FlowCardCountryCondition {
    /**
    * The type of match made for this rule.
    */
    'name': FlowCardCountryCondition.NameEnum;
    /**
    * The comparison to make on the `value`.
    */
    'operator': FlowCardCountryCondition.OperatorEnum;
    /**
    * Countries to compare the card originating country to in `ISO-3166` 2 character format.
    */
    'value': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "FlowCardCountryCondition.NameEnum"
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "FlowCardCountryCondition.OperatorEnum"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return FlowCardCountryCondition.attributeTypeMap;
    }
}

export namespace FlowCardCountryCondition {
    export enum NameEnum {
        CardCountry = <any> 'card_country'
    }
    export enum OperatorEnum {
        OneOf = <any> 'is_one_of',
        NotOneOf = <any> 'is_not_one_of'
    }
}
