/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AntiFraudServiceDefinitionFieldsInner } from './antiFraudServiceDefinitionFieldsInner';

/**
* An available gift card service that can be configured.
*/
export class GiftCardServiceDefinition {
    /**
    * The ID of the gift card service definition.
    */
    'id'?: string;
    /**
    * `gift-card-service-definition`.
    */
    'type'?: GiftCardServiceDefinition.TypeEnum = GiftCardServiceDefinition.TypeEnum.GiftCardServiceDefinition;
    /**
    * The display name of this service.
    */
    'displayName'?: string;
    /**
    * A list of fields that need to be submitted when activating the payment. service.
    */
    'fields'?: Array<AntiFraudServiceDefinitionFieldsInner>;
    /**
    * An icon to display for the payment service.
    */
    'iconUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "GiftCardServiceDefinition.TypeEnum"
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<AntiFraudServiceDefinitionFieldsInner>"
        },
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GiftCardServiceDefinition.attributeTypeMap;
    }
}

export namespace GiftCardServiceDefinition {
    export enum TypeEnum {
        GiftCardServiceDefinition = <any> 'gift-card-service-definition'
    }
}
