/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GiftCardServiceUpdateRequestFieldsInner } from './giftCardServiceUpdateRequestFieldsInner';

/**
* Request body for updating a gift card service.
*/
export class GiftCardServiceUpdateRequest {
    /**
    * A custom name for the gift card service. This will be shown in the Admin UI.
    */
    'displayName'?: string;
    /**
    * A list of fields, each containing a key-value pair for each field defined by the definition for this gift card service.
    */
    'fields'?: Array<GiftCardServiceUpdateRequestFieldsInner>;
    /**
    * Defines if this service is currently active or not.
    */
    'active'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<GiftCardServiceUpdateRequestFieldsInner>"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return GiftCardServiceUpdateRequest.attributeTypeMap;
    }
}

