/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Check the balance for a non-stored gift card.
*/
export class GiftCardBalanceNewRequest {
    /**
    * The 16-19 digit number for this gift card.
    */
    'number': string;
    /**
    * The PIN for this gift card.
    */
    'pin': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "pin",
            "baseName": "pin",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GiftCardBalanceNewRequest.attributeTypeMap;
    }
}

