/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A snapshot of a gift card used in a transaction.
*/
export class GiftCardSnapshot {
    /**
    * The type of this resource.
    */
    'type'?: GiftCardSnapshot.TypeEnum;
    /**
    * The ID of this gift card. This may be `null` if the gift card is not stored.
    */
    'id'?: string | null;
    /**
    * The first 6 digits of the full gift card number.
    */
    'bin'?: string;
    /**
    * The 3 digits after the `bin` of the full gift card number.
    */
    'subBin'?: string;
    /**
    * The last 4 digits for the gift card.
    */
    'last4'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GiftCardSnapshot.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "bin",
            "baseName": "bin",
            "type": "string"
        },
        {
            "name": "subBin",
            "baseName": "sub_bin",
            "type": "string"
        },
        {
            "name": "last4",
            "baseName": "last4",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GiftCardSnapshot.attributeTypeMap;
    }
}

export namespace GiftCardSnapshot {
    export enum TypeEnum {
        GiftCard = <any> 'gift-card'
    }
}
