/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Details for a Google Pay payment method.
*/
export class GooglePayRequest {
    /**
    * `googlepay`.
    */
    'method': GooglePayRequest.MethodEnum;
    /**
    * The encrypted (opaque) token returned by the Google Pay API that represents a payment method.
    */
    'token': object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "GooglePayRequest.MethodEnum"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return GooglePayRequest.attributeTypeMap;
    }
}

export namespace GooglePayRequest {
    export enum MethodEnum {
        Googlepay = <any> 'googlepay'
    }
}
