/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MerchantProfileSummaryAmex } from './merchantProfileSummaryAmex';
import { MerchantProfileSummaryDankort } from './merchantProfileSummaryDankort';
import { MerchantProfileSummaryDiscover } from './merchantProfileSummaryDiscover';
import { MerchantProfileSummaryJcb } from './merchantProfileSummaryJcb';
import { MerchantProfileSummaryMastercard } from './merchantProfileSummaryMastercard';
import { MerchantProfileSummaryUnionpay } from './merchantProfileSummaryUnionpay';
import { MerchantProfileSummaryVisa } from './merchantProfileSummaryVisa';

/**
* Merchant profile for the different card schemes.
*/
export class MerchantProfileSummary {
    'amex'?: MerchantProfileSummaryAmex | null;
    'dankort'?: MerchantProfileSummaryDankort | null;
    'discover'?: MerchantProfileSummaryDiscover | null;
    'jcb'?: MerchantProfileSummaryJcb | null;
    'mastercard'?: MerchantProfileSummaryMastercard | null;
    'unionpay'?: MerchantProfileSummaryUnionpay | null;
    'visa'?: MerchantProfileSummaryVisa | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amex",
            "baseName": "amex",
            "type": "MerchantProfileSummaryAmex"
        },
        {
            "name": "dankort",
            "baseName": "dankort",
            "type": "MerchantProfileSummaryDankort"
        },
        {
            "name": "discover",
            "baseName": "discover",
            "type": "MerchantProfileSummaryDiscover"
        },
        {
            "name": "jcb",
            "baseName": "jcb",
            "type": "MerchantProfileSummaryJcb"
        },
        {
            "name": "mastercard",
            "baseName": "mastercard",
            "type": "MerchantProfileSummaryMastercard"
        },
        {
            "name": "unionpay",
            "baseName": "unionpay",
            "type": "MerchantProfileSummaryUnionpay"
        },
        {
            "name": "visa",
            "baseName": "visa",
            "type": "MerchantProfileSummaryVisa"
        }    ];

    static getAttributeTypeMap() {
        return MerchantProfileSummary.attributeTypeMap;
    }
}

