/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NetworkTokenCryptogramProvisionSucceededContext } from './networkTokenCryptogramProvisionSucceededContext';

/**
* This event logs the request and response details of HTTP calls made to provision a network token, in case the call succeeded.
*/
export class NetworkTokenProvisionSucceeded {
    /**
    * The type of this resource. Is always `transaction-event`.
    */
    'type'?: NetworkTokenProvisionSucceeded.TypeEnum;
    /**
    * The unique identifier for this event.
    */
    'id'?: string;
    /**
    * The name of this resource. Is always `network-token-provision-succeeded`.
    */
    'name'?: NetworkTokenProvisionSucceeded.NameEnum;
    /**
    * The date and time when this event was created in our system.
    */
    'createdAt'?: Date;
    'context'?: NetworkTokenCryptogramProvisionSucceededContext;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "NetworkTokenProvisionSucceeded.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "NetworkTokenProvisionSucceeded.NameEnum"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "NetworkTokenCryptogramProvisionSucceededContext"
        }    ];

    static getAttributeTypeMap() {
        return NetworkTokenProvisionSucceeded.attributeTypeMap;
    }
}

export namespace NetworkTokenProvisionSucceeded {
    export enum TypeEnum {
        TransactionEvent = <any> 'transaction-event'
    }
    export enum NameEnum {
        NetworkTokenProvisionSucceeded = <any> 'network-token-provision-succeeded'
    }
}
