/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum PaymentOptionCardSchemeApplePay {
    Amex = <any> 'amex',
    CartesBancaires = <any> 'cartesBancaires',
    Discover = <any> 'discover',
    Eftpos = <any> 'eftpos',
    Electron = <any> 'electron',
    Elo = <any> 'elo',
    Interac = <any> 'interac',
    Jcb = <any> 'jcb',
    Mada = <any> 'mada',
    Maestro = <any> 'maestro',
    MasterCard = <any> 'masterCard',
    PrivateLabel = <any> 'privateLabel',
    Visa = <any> 'visa',
    VPay = <any> 'vPay'
}
