/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentOptionContext } from './paymentOptionContext';

/**
* An available payment option for a locale.
*/
export class PaymentOption {
    /**
    * `payment-option`.
    */
    'type'?: PaymentOption.TypeEnum;
    /**
    * The type of payment method that is available.
    */
    'method'?: PaymentOption.MethodEnum;
    /**
    * An icon to display for the payment option.
    */
    'iconUrl'?: string | null;
    /**
    * The mode to use with this payment option.
    */
    'mode'?: PaymentOption.ModeEnum;
    /**
    * A label that describes this payment option. This label is returned in the language defined by the `locale` query parameter. The label can be used to display a list of payment options to the buyer in their language.
    */
    'label'?: string;
    /**
    * A flag to indicate if storing the payment method is supported.
    */
    'canStorePaymentMethod'?: boolean;
    /**
    * A flag to indicate if delayed capture is supported.
    */
    'canDelayCapture'?: boolean;
    'context'?: PaymentOptionContext;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PaymentOption.TypeEnum"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "PaymentOption.MethodEnum"
        },
        {
            "name": "iconUrl",
            "baseName": "icon_url",
            "type": "string"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "PaymentOption.ModeEnum"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "canStorePaymentMethod",
            "baseName": "can_store_payment_method",
            "type": "boolean"
        },
        {
            "name": "canDelayCapture",
            "baseName": "can_delay_capture",
            "type": "boolean"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "PaymentOptionContext"
        }    ];

    static getAttributeTypeMap() {
        return PaymentOption.attributeTypeMap;
    }
}

export namespace PaymentOption {
    export enum TypeEnum {
        PaymentOption = <any> 'payment-option'
    }
    export enum MethodEnum {
        Afterpay = <any> 'afterpay',
        Alipay = <any> 'alipay',
        Alipayhk = <any> 'alipayhk',
        Applepay = <any> 'applepay',
        Bacs = <any> 'bacs',
        Banked = <any> 'banked',
        Becs = <any> 'becs',
        Bitpay = <any> 'bitpay',
        Boleto = <any> 'boleto',
        Boost = <any> 'boost',
        Card = <any> 'card',
        Cashapp = <any> 'cashapp',
        Chaseorbital = <any> 'chaseorbital',
        Clearpay = <any> 'clearpay',
        ClickToPay = <any> 'click-to-pay',
        Dana = <any> 'dana',
        Dcb = <any> 'dcb',
        Dlocal = <any> 'dlocal',
        Ebanx = <any> 'ebanx',
        Gcash = <any> 'gcash',
        Giropay = <any> 'giropay',
        Gocardless = <any> 'gocardless',
        Googlepay = <any> 'googlepay',
        Gopay = <any> 'gopay',
        Grabpay = <any> 'grabpay',
        Ideal = <any> 'ideal',
        Kakaopay = <any> 'kakaopay',
        Klarna = <any> 'klarna',
        Laybuy = <any> 'laybuy',
        Linkaja = <any> 'linkaja',
        Maybankqrpay = <any> 'maybankqrpay',
        Multibanco = <any> 'multibanco',
        Oney3x = <any> 'oney_3x',
        Oney4x = <any> 'oney_4x',
        Oney6x = <any> 'oney_6x',
        Oney10x = <any> 'oney_10x',
        Oney12x = <any> 'oney_12x',
        Ovo = <any> 'ovo',
        Oxxo = <any> 'oxxo',
        Payid = <any> 'payid',
        Paymaya = <any> 'paymaya',
        Paypal = <any> 'paypal',
        Paypalpaylater = <any> 'paypalpaylater',
        Payto = <any> 'payto',
        Venmo = <any> 'venmo',
        Pix = <any> 'pix',
        Rabbitlinepay = <any> 'rabbitlinepay',
        Scalapay = <any> 'scalapay',
        Sepa = <any> 'sepa',
        Shopeepay = <any> 'shopeepay',
        Singteldash = <any> 'singteldash',
        Sofort = <any> 'sofort',
        Stripedd = <any> 'stripedd',
        Thaiqr = <any> 'thaiqr',
        Touchngo = <any> 'touchngo',
        Truemoney = <any> 'truemoney',
        Trustly = <any> 'trustly',
        Trustlyeurope = <any> 'trustlyeurope',
        Givingblock = <any> 'givingblock',
        Wechat = <any> 'wechat',
        Zippay = <any> 'zippay',
        Bancontact = <any> 'bancontact',
        Eps = <any> 'eps',
        Linepay = <any> 'linepay',
        Razorpay = <any> 'razorpay',
        Multipago = <any> 'multipago',
        Waave = <any> 'waave',
        Smartpay = <any> 'smartpay',
        Vipps = <any> 'vipps'
    }
    export enum ModeEnum {
        Card = <any> 'card',
        Redirect = <any> 'redirect',
        Applepay = <any> 'applepay',
        Googlepay = <any> 'googlepay'
    }
}
