/**
 * Gr4vy API (Beta)
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentServiceUpdate } from './paymentServiceUpdate';
import { PaymentServiceUpdateFields } from './paymentServiceUpdateFields';

/**
* Request body for activating a payment service.
*/
export class PaymentServiceRequest {
    /**
    * The ID of the payment service to use.
    */
    'payment_service_definition_id': string;
    /**
    * A custom name for the payment service. This will be shown in the Admin UI.
    */
    'display_name': string;
    /**
    * A list of fields, each containing a key-value pair for each field defined by the definition for this payment service.
    */
    'fields': Array<PaymentServiceUpdateFields>;
    /**
    * A list of countries that this payment service needs to support in ISO two-letter code format.
    */
    'accepted_countries': Array<string>;
    /**
    * A list of currencies that this payment service needs to support in ISO 4217 three-letter code format.
    */
    'accepted_currencies': Array<string>;
    /**
    * Defines if this payment service uses the service\'s test/sandbox environment.
    */
    'use_test_environment': boolean;
    /**
    * The numeric rank of a payment service. Payment services with a lower position value are processed first. When a payment services is inserted at a position, any payment services with the the same value or higher are shifted down a position accordingly. When left out, the payment service is inserted at the end of the list.
    */
    'position'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "payment_service_definition_id",
            "baseName": "payment_service_definition_id",
            "type": "string"
        },
        {
            "name": "display_name",
            "baseName": "display_name",
            "type": "string"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<PaymentServiceUpdateFields>"
        },
        {
            "name": "accepted_countries",
            "baseName": "accepted_countries",
            "type": "Array<string>"
        },
        {
            "name": "accepted_currencies",
            "baseName": "accepted_currencies",
            "type": "Array<string>"
        },
        {
            "name": "use_test_environment",
            "baseName": "use_test_environment",
            "type": "boolean"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PaymentServiceRequest.attributeTypeMap;
    }
}

