/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Additional context specific to the payment option. This is currently only returned for Apple Pay and Google Pay.
*/
export class PaymentOptionContext {
    /**
    * Display name of the merchant as registered with the digital wallet provider.
    */
    'merchantName'?: string;
    /**
    * Card schemes supported by the digital wallet provider.
    */
    'supportedSchemes'?: Array<String>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "merchantName",
            "baseName": "merchant_name",
            "type": "string"
        },
        {
            "name": "supportedSchemes",
            "baseName": "supported_schemes",
            "type": "Array<Undefined>"
        }    ];

    static getAttributeTypeMap() {
        return PaymentOptionContext.attributeTypeMap;
    }
}

