/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaymentServiceVerifyFields } from './paymentServiceVerifyFields';

/**
* Request body for verifying credentials against a payment service.
*/
export class PaymentServiceVerify {
    /**
    * The ID of the payment service to use.
    */
    'paymentServiceDefinitionId': string;
    /**
    * The ID of the payment service. Required if sending a partial set of credentials in the `fields` property.
    */
    'paymentServiceId'?: string;
    /**
    * A list of fields where each field is a key-value pair that represents a defined field in the definition of the payment service. You are not required to send the full list of fields if the credentials for the payment service are already stored. For example, if your credentials for `stripe-card` are stored and you only provide a `secret_key` in the request, it will override the stored `secret_key` and verify the resulting set of credentials against the payment service.
    */
    'fields': Array<PaymentServiceVerifyFields>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentServiceDefinitionId",
            "baseName": "payment_service_definition_id",
            "type": "string"
        },
        {
            "name": "paymentServiceId",
            "baseName": "payment_service_id",
            "type": "string"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<PaymentServiceVerifyFields>"
        }    ];

    static getAttributeTypeMap() {
        return PaymentServiceVerify.attributeTypeMap;
    }
}

