/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The temporary signed URL to download the result of a report execution and its expiration date and time.
*/
export class ReportExecutionUrl {
    /**
    * The URL to download the report execution.
    */
    'url'?: string;
    /**
    * The date and time when the download URL expires.
    */
    'expiresAt'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return ReportExecutionUrl.attributeTypeMap;
    }
}

