/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The filters for the report.
*/
export class ReportSpecParamsFilters {
    /**
    * A list of status\' to filter by.
    */
    'status'?: Array<string>;
    /**
    * The created date and time to filter by.
    */
    'createdAt'?: string;
    /**
    * The updated date and time to filter by.
    */
    'updatedAt'?: string;
    /**
    * The authorized date and time to filter by.
    */
    'authorizedAt'?: string;
    /**
    * The captured date and time to filter by.
    */
    'capturedAt'?: string;
    /**
    * The voided date and time to filter by.
    */
    'voidedAt'?: string;
    /**
    * A list of currencies to filter by.
    */
    'currency'?: Array<string>;
    /**
    * A list of methods to filter by.
    */
    'method'?: Array<string>;
    /**
    * A list of schemes to filter by.
    */
    'scheme'?: Array<string>;
    /**
    * A list of metadata to filter by.
    */
    'metadata'?: Array<string>;
    /**
    * A boolean indicating transactions with subsequent payments to filter by.
    */
    'isSubsequentPayment'?: boolean;
    /**
    * A boolean indicating transactions initiated by the merchant to filter by.
    */
    'merchantInitiated'?: boolean;
    /**
    * A list of transaction sources to filter by.
    */
    'paymentSource'?: Array<string>;
    /**
    * A list of 3DS status to filter by.
    */
    'threeDSecureStatus'?: Array<string>;
    /**
    * A list of electric commerce indicators to filter by.
    */
    'threeDSecureEci'?: Array<string>;
    /**
    * A list of 3DS responses to filter by.
    */
    'threeDSecureAuthResp'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "Array<string>"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "authorizedAt",
            "baseName": "authorized_at",
            "type": "string"
        },
        {
            "name": "capturedAt",
            "baseName": "captured_at",
            "type": "string"
        },
        {
            "name": "voidedAt",
            "baseName": "voided_at",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "Array<string>"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "Array<string>"
        },
        {
            "name": "scheme",
            "baseName": "scheme",
            "type": "Array<string>"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "Array<string>"
        },
        {
            "name": "isSubsequentPayment",
            "baseName": "is_subsequent_payment",
            "type": "boolean"
        },
        {
            "name": "merchantInitiated",
            "baseName": "merchant_initiated",
            "type": "boolean"
        },
        {
            "name": "paymentSource",
            "baseName": "payment_source",
            "type": "Array<string>"
        },
        {
            "name": "threeDSecureStatus",
            "baseName": "three_d_secure_status",
            "type": "Array<string>"
        },
        {
            "name": "threeDSecureEci",
            "baseName": "three_d_secure_eci",
            "type": "Array<string>"
        },
        {
            "name": "threeDSecureAuthResp",
            "baseName": "three_d_secure_auth_resp",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ReportSpecParamsFilters.attributeTypeMap;
    }
}

