/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A user session.
*/
export class Session {
    /**
    * `auth.session`.
    */
    'type'?: Session.TypeEnum;
    /**
    * `bearer`.
    */
    'tokenType'?: Session.TokenTypeEnum;
    /**
    * A server-signed JWT that can be used as the bearer token in any API calls.
    */
    'accessToken'?: string;
    /**
    * A server-signed JWT that can be used as the bearer token to refresh the access token.
    */
    'refreshToken'?: string;
    /**
    * The time in seconds in seconds by which the `access_token` token will expire.
    */
    'expiresIn'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "Session.TypeEnum"
        },
        {
            "name": "tokenType",
            "baseName": "token_type",
            "type": "Session.TokenTypeEnum"
        },
        {
            "name": "accessToken",
            "baseName": "access_token",
            "type": "string"
        },
        {
            "name": "refreshToken",
            "baseName": "refresh_token",
            "type": "string"
        },
        {
            "name": "expiresIn",
            "baseName": "expires_in",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Session.attributeTypeMap;
    }
}

export namespace Session {
    export enum TypeEnum {
        AuthSession = <any> 'auth.session'
    }
    export enum TokenTypeEnum {
        Bearer = <any> 'bearer'
    }
}
