/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ThreeDSecurePreparationRequestEventContext } from './threeDSecurePreparationRequestEventContext';

/**
* The result and raw data for a 3DS pre-authorization call.
*/
export class ThreeDSecurePreparationRequestEvent {
    /**
    * The type of this resource. Is always `transaction-event`.
    */
    'type'?: ThreeDSecurePreparationRequestEvent.TypeEnum;
    /**
    * The unique identifier for this event.
    */
    'id'?: string;
    /**
    * The name of this resource. Is always `three-d-secure-preparation-request`.
    */
    'name'?: ThreeDSecurePreparationRequestEvent.NameEnum;
    /**
    * The date and time when this transaction was created in our system.
    */
    'createdAt'?: Date;
    'context'?: ThreeDSecurePreparationRequestEventContext;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ThreeDSecurePreparationRequestEvent.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "ThreeDSecurePreparationRequestEvent.NameEnum"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "ThreeDSecurePreparationRequestEventContext"
        }    ];

    static getAttributeTypeMap() {
        return ThreeDSecurePreparationRequestEvent.attributeTypeMap;
    }
}

export namespace ThreeDSecurePreparationRequestEvent {
    export enum TypeEnum {
        TransactionEvent = <any> 'transaction-event'
    }
    export enum NameEnum {
        ThreeDSecurePreparationRequest = <any> 'three-d-secure-preparation-request'
    }
}
