/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ThreeDSecureDataV2AllOf {
    /**
    * The transaction status from the challenge result (not required for frictionless).
    */
    'authenticationResponse'?: string;
    /**
    * The transaction identifier.
    */
    'directoryTransactionId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "authenticationResponse",
            "baseName": "authentication_response",
            "type": "string"
        },
        {
            "name": "directoryTransactionId",
            "baseName": "directory_transaction_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ThreeDSecureDataV2AllOf.attributeTypeMap;
    }
}

