/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ThreeDSecureV2 {
    /**
    * The cardholder authentication value or AAV.
    */
    'cavv'?: string | null;
    /**
    * The ecommerce indicator for the 3DS transaction.
    */
    'eci'?: string | null;
    /**
    * The version of 3-D Secure that was used.
    */
    'version'?: string;
    /**
    * The transaction status after a the 3DS challenge. This will be null in case of a frictionless 3DS flow.
    */
    'authenticationResponse'?: ThreeDSecureV2.AuthenticationResponseEnum;
    /**
    * The transaction status received as part of the authentication request.
    */
    'directoryResponse'?: ThreeDSecureV2.DirectoryResponseEnum;
    /**
    * The transaction identifier.
    */
    'directoryTransactionId'?: string | null;
    /**
    * The reason identifier for a declined transaction.
    */
    'transactionReason'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cavv",
            "baseName": "cavv",
            "type": "string"
        },
        {
            "name": "eci",
            "baseName": "eci",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "authenticationResponse",
            "baseName": "authentication_response",
            "type": "ThreeDSecureV2.AuthenticationResponseEnum"
        },
        {
            "name": "directoryResponse",
            "baseName": "directory_response",
            "type": "ThreeDSecureV2.DirectoryResponseEnum"
        },
        {
            "name": "directoryTransactionId",
            "baseName": "directory_transaction_id",
            "type": "string"
        },
        {
            "name": "transactionReason",
            "baseName": "transaction_reason",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ThreeDSecureV2.attributeTypeMap;
    }
}

export namespace ThreeDSecureV2 {
    export enum AuthenticationResponseEnum {
        Y = <any> 'Y',
        A = <any> 'A',
        N = <any> 'N',
        R = <any> 'R',
        U = <any> 'U'
    }
    export enum DirectoryResponseEnum {
        C = <any> 'C',
        Y = <any> 'Y',
        A = <any> 'A',
        N = <any> 'N',
        R = <any> 'R',
        U = <any> 'U'
    }
}
