/**
 * Gr4vy API (Beta)
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Details for a previously tokenized payment method.
*/
export class TokenizedRequest {
    /**
    * `id`.
    */
    'method': TokenizedRequest.MethodEnum;
    /**
    * A ID that represents a previously tokenized payment method. This token can represent any type of payment method.
    */
    'id': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "TokenizedRequest.MethodEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TokenizedRequest.attributeTypeMap;
    }
}

export namespace TokenizedRequest {
    export enum MethodEnum {
        Id = <any> 'id'
    }
}
