/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Checkout Session payment method details to use in a transaction.
*/
export class TransactionCheckoutSessionRequest {
    /**
    * `checkout-session`.
    */
    'method': TransactionCheckoutSessionRequest.MethodEnum;
    /**
    * The ID of the Checkout Session.
    */
    'id': string;
    /**
    * An external identifier that can be used to match the card against your own records. This can only be set if the `store` flag is set to `true`.
    */
    'externalIdentifier'?: string | null;
    /**
    * We strongly recommend providing a `redirect_url` either when 3-D Secure is enabled and `three_d_secure_data` is not provided, or when using connections where 3DS is enabled. This value will be appended with both a transaction ID and status (e.g. `https://example.com/callback?gr4vy_transaction_id=123 &gr4vy_transaction_status=capture_succeeded`) after 3-D Secure has completed. For those cases, if the value is not present, the transaction will be marked as failed.
    */
    'redirectUrl'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "TransactionCheckoutSessionRequest.MethodEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "externalIdentifier",
            "baseName": "external_identifier",
            "type": "string"
        },
        {
            "name": "redirectUrl",
            "baseName": "redirect_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TransactionCheckoutSessionRequest.attributeTypeMap;
    }
}

export namespace TransactionCheckoutSessionRequest {
    export enum MethodEnum {
        CheckoutSession = <any> 'checkout-session'
    }
}
