/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Card payment method details to use in a transaction.
*/
export class TransactionCardRequest {
    /**
    * `card`.
    */
    'method': TransactionCardRequest.MethodEnum;
    /**
    * The 13-19 digit number for this card as it can be found on the front of the card.
    */
    'number': string;
    /**
    * The expiration date of the card, formatted `MM/YY`.
    */
    'expirationDate': string;
    /**
    * The 3 or 4 digit security code often found on the card. This often referred to as the CVV or CVD.
    */
    'securityCode': string;
    /**
    * An external identifier that can be used to match the card against your own records. This can only be set if the `store` flag is set to `true`.
    */
    'externalIdentifier'?: string | null;
    /**
    * We strongly recommend providing a `redirect_url` either when 3-D Secure is enabled and `three_d_secure_data` is not provided, or when using connections where 3DS is enabled. This value will be appended with both a transaction ID and status (e.g. `https://example.com/callback?gr4vy_transaction_id=123 &gr4vy_transaction_status=capture_succeeded`) after 3-D Secure has completed. For those cases, if the value is not present, the transaction will be marked as failed.
    */
    'redirectUrl'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "TransactionCardRequest.MethodEnum"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "expirationDate",
            "baseName": "expiration_date",
            "type": "string"
        },
        {
            "name": "securityCode",
            "baseName": "security_code",
            "type": "string"
        },
        {
            "name": "externalIdentifier",
            "baseName": "external_identifier",
            "type": "string"
        },
        {
            "name": "redirectUrl",
            "baseName": "redirect_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TransactionCardRequest.attributeTypeMap;
    }
}

export namespace TransactionCardRequest {
    export enum MethodEnum {
        Card = <any> 'card'
    }
}
