/**
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TransactionsReportSpecParams } from './transactionsReportSpecParams';

/**
* The specification of a transactions report.
*/
export class TransactionsReportSpec {
    /**
    * The model (dataset) that the data used for the report is retrieved from.
    */
    'model': TransactionsReportSpec.ModelEnum;
    'params': TransactionsReportSpecParams;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "model",
            "baseName": "model",
            "type": "TransactionsReportSpec.ModelEnum"
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "TransactionsReportSpecParams"
        }    ];

    static getAttributeTypeMap() {
        return TransactionsReportSpec.attributeTypeMap;
    }
}

export namespace TransactionsReportSpec {
    export enum ModelEnum {
        Transactions = <any> 'transactions'
    }
}
